/**
 * MetadataCatalog.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package org.glite.wsdl.services.org_glite_data_catalog_service_meta;

public interface MetadataCatalog extends java.rmi.Remote {
    public void createEntry(org.glite.wsdl.services.org_glite_data_catalog.StringPair[] entries) throws java.rmi.RemoteException, org.glite.wsdl.services.org_glite_data_catalog.AuthorizationException, org.glite.wsdl.services.org_glite_data_catalog.ExistsException, org.glite.wsdl.services.org_glite_data_catalog.NotExistsException, org.glite.wsdl.services.org_glite_data_catalog.InvalidArgumentException, org.glite.wsdl.services.org_glite_data_catalog.InternalException;
    public void removeEntry(java.lang.String[] items) throws java.rmi.RemoteException, org.glite.wsdl.services.org_glite_data_catalog.AuthorizationException, org.glite.wsdl.services.org_glite_data_catalog.NotExistsException, org.glite.wsdl.services.org_glite_data_catalog.InternalException;
    public org.glite.wsdl.services.org_glite_data_catalog.Attribute[] getAttributes(java.lang.String item, java.lang.String[] attributeNames) throws java.rmi.RemoteException, org.glite.wsdl.services.org_glite_data_catalog.AuthorizationException, org.glite.wsdl.services.org_glite_data_catalog.NotExistsException, org.glite.wsdl.services.org_glite_data_catalog.InternalException;
    public java.lang.String[] query(java.lang.String query, java.lang.String type, int limit, int offset) throws java.rmi.RemoteException, org.glite.wsdl.services.org_glite_data_catalog.AuthorizationException, org.glite.wsdl.services.org_glite_data_catalog.InvalidArgumentException, org.glite.wsdl.services.org_glite_data_catalog.InternalException;
    public void setAttributes(java.lang.String item, org.glite.wsdl.services.org_glite_data_catalog.Attribute[] attributes) throws java.rmi.RemoteException, org.glite.wsdl.services.org_glite_data_catalog.AuthorizationException, org.glite.wsdl.services.org_glite_data_catalog.NotExistsException, org.glite.wsdl.services.org_glite_data_catalog.InvalidArgumentException, org.glite.wsdl.services.org_glite_data_catalog.InternalException;
    public void clearAttributes(java.lang.String item, java.lang.String[] attributeNames) throws java.rmi.RemoteException, org.glite.wsdl.services.org_glite_data_catalog.AuthorizationException, org.glite.wsdl.services.org_glite_data_catalog.NotExistsException, org.glite.wsdl.services.org_glite_data_catalog.InternalException;
    public org.glite.wsdl.services.org_glite_data_catalog.Attribute[] listAttributes(java.lang.String item) throws java.rmi.RemoteException, org.glite.wsdl.services.org_glite_data_catalog.AuthorizationException, org.glite.wsdl.services.org_glite_data_catalog.NotExistsException, org.glite.wsdl.services.org_glite_data_catalog.InternalException;
    public java.lang.String getVersion() throws java.rmi.RemoteException;
    public java.lang.String getSchemaVersion() throws java.rmi.RemoteException;
    public java.lang.String getInterfaceVersion() throws java.rmi.RemoteException;
    public java.lang.String getServiceMetadata(java.lang.String key) throws java.rmi.RemoteException;
    public void createSchema(java.lang.String schemaName, org.glite.wsdl.services.org_glite_data_catalog.Attribute[] attributes) throws java.rmi.RemoteException, org.glite.wsdl.services.org_glite_data_catalog.AuthorizationException, org.glite.wsdl.services.org_glite_data_catalog.ExistsException, org.glite.wsdl.services.org_glite_data_catalog.InvalidArgumentException, org.glite.wsdl.services.org_glite_data_catalog.InternalException;
    public void addSchemaAttributes(java.lang.String schemaName, org.glite.wsdl.services.org_glite_data_catalog.Attribute[] attributes) throws java.rmi.RemoteException, org.glite.wsdl.services.org_glite_data_catalog.AuthorizationException, org.glite.wsdl.services.org_glite_data_catalog.ExistsException, org.glite.wsdl.services.org_glite_data_catalog.NotExistsException, org.glite.wsdl.services.org_glite_data_catalog.InvalidArgumentException, org.glite.wsdl.services.org_glite_data_catalog.InternalException;
    public void removeSchemaAttributes(java.lang.String schemaName, java.lang.String[] attributeNames) throws java.rmi.RemoteException, org.glite.wsdl.services.org_glite_data_catalog.AuthorizationException, org.glite.wsdl.services.org_glite_data_catalog.NotExistsException, org.glite.wsdl.services.org_glite_data_catalog.InternalException;
    public void dropSchema(java.lang.String schemaName) throws java.rmi.RemoteException, org.glite.wsdl.services.org_glite_data_catalog.AuthorizationException, org.glite.wsdl.services.org_glite_data_catalog.NotExistsException, org.glite.wsdl.services.org_glite_data_catalog.InternalException;
    public java.lang.String[] listSchemas() throws java.rmi.RemoteException, org.glite.wsdl.services.org_glite_data_catalog.AuthorizationException, org.glite.wsdl.services.org_glite_data_catalog.InternalException;
    public org.glite.wsdl.services.org_glite_data_catalog.Attribute[] describeSchema(java.lang.String schemaName) throws java.rmi.RemoteException, org.glite.wsdl.services.org_glite_data_catalog.AuthorizationException, org.glite.wsdl.services.org_glite_data_catalog.NotExistsException, org.glite.wsdl.services.org_glite_data_catalog.InternalException;
    public void checkPermission(java.lang.String[] items, org.glite.wsdl.services.org_glite_data_catalog.Perm perm) throws java.rmi.RemoteException, org.glite.wsdl.services.org_glite_data_catalog.AuthorizationException, org.glite.wsdl.services.org_glite_data_catalog.InternalException;
    public org.glite.wsdl.services.org_glite_data_catalog.PermissionEntry[] getPermission(java.lang.String[] items) throws java.rmi.RemoteException, org.glite.wsdl.services.org_glite_data_catalog.AuthorizationException, org.glite.wsdl.services.org_glite_data_catalog.NotExistsException, org.glite.wsdl.services.org_glite_data_catalog.InvalidArgumentException, org.glite.wsdl.services.org_glite_data_catalog.InternalException;
    public void setPermission(org.glite.wsdl.services.org_glite_data_catalog.PermissionEntry[] permissions) throws java.rmi.RemoteException, org.glite.wsdl.services.org_glite_data_catalog.AuthorizationException, org.glite.wsdl.services.org_glite_data_catalog.NotExistsException, org.glite.wsdl.services.org_glite_data_catalog.InvalidArgumentException, org.glite.wsdl.services.org_glite_data_catalog.InternalException;
}
